# This file was autogenerated by base/version_git.sh
struct GitVersionInfo
    commit::String
    commit_short::String
    branch::String
    build_number::Int
    date_string::String
    tagged_commit::Bool
    fork_master_distance::Int
    fork_master_timestamp::Float64
    build_system_commit::String
    build_system_commit_short::String
end

const GIT_VERSION_INFO = GitVersionInfo(
    "3120989f39bb7ef7863c4aab8ab1227cf71eec66",
    "3120989f39b",
    "v1.10.0",
    0,
    "2023-12-25 18:01 UTC",
    true,
    253,
    1688376058.0,
    "70bde73f6cb17d4381b62236fc2d96b1c7acbba7",
    "70bde73",
)
